<?php
/**
 * GE Capital HQ Commercial Media | Genius 3.0
 *
 * Copyright (c) 2013 General Electric Company
 *
 * This file contains GE CONFIDENTIAL Information
 * Use, disclosure or reproduction is prohibited.
 *
 * @version   SVN $Revision$
 * @author    GE Company / GE Capital Genius 3.0
 * @copyright Copyright (c) 2013 General Electric Company
 */
?><!doctype html>

<html>

    <head>
        <title>GENIUS 3.0 | MVC</title>
    </head>

    <body>
        <h1>Default Module</h1>
    </body>

</html>
