<?php
/**
 * GE Capital HQ Commercial Media | GENIUS
 *
 * Copyright (c) 2013 General Electric Company
 *
 * This file contains GE CONFIDENTIAL Information
 * Use, disclosure or reproduction is prohibited.
 *
 * @version   SVN $Revision$
 * @author    GE Company / @Capital HQ Genius Dev
 * @copyright Copyright (c) 2013 General Electric Company
 */
?>
<!doctype html>
<html>
    <head>
        <title>GENIUS Maintenance</title>
        <link rel=stylesheet type=text/css href="/css/app.css">
        
    </head>
    <body data-sso=$SSO data-key=$api>
         <header id="top">
        <div class="header-Lv1-controls">
            <h1><a href="/home"><img alt="Genius" src="/images/genius_logo.png"></a></h1>
        </div>
        </header>
    <div id="container">
        <div id="cError" class="paddedContainer">
            <section class="contentBlock error">            
                <h1>Site Update in Progress</h1>
                <p>
                    We're sorry, but we are currently performing maintenance to GENIUS. Please try again later.
                </p>                
                <p>
                    We apologize for any inconvenience.
                </p>               
            </section>  
            </div>
       </div>   
    </body>
</html>

