<?php
/**
 * GE Capital HQ Commercial Media | GENIUS
 *
 * Copyright (c) 2013 General Electric Company
 *
 * This file contains GE CONFIDENTIAL Information
 * Use, disclosure or reproduction is prohibited.
 *
 * @version   SVN $Revision$
 * @author    GE Company / @Capital HQ Genius Dev
 * @copyright Copyright (c) 2013 General Electric Company
 */
?>
<!doctype html>
<html>
    <head>
        <title>GENIUS Access Denied</title>
        <link rel=stylesheet type=text/css href="/css/app.css">
        
    </head>
    <script type="text/javascript">
        var domain = '.' + document.domain.split('.').slice(-2).join('.');
	   document.cookie = "SMSESSION=; expires=Thu, 01-Jan-70 00:00:01 GMT;" +
	   "domain=" + domain + "; path=/";	   	   
    </script>
    <body data-sso=$SSO data-key=$api>
                
            <header id="top">
		<div class="header-Lv1-controls">
			<h1><a href="/home"><img alt="Genius" src="/images/genius_logo.png"></a></h1>
		</div>
		</header>
	<div id="container">
		<div id="cError" class="paddedContainer">
			<section class="contentBlock error">
				<h1>Access Denied.</h1>
				<p>
                    Your Business has not yet been on boarded to the GENIUS application.  
                </p>
                <p>
                    If you are receiving this message in error, please contact your local help desk.
                </p>
			</section>	
    		</div>
	   </div>        
    </body>
</html>

