<?php
/**
 * GE Capital HQ Commercial Media | GENIUS
 *
 * Copyright (c) 2013 General Electric Company
 *
 * This file contains GE CONFIDENTIAL Information
 * Use, disclosure or reproduction is prohibited.
 *
 * @version   SVN $Revision$
 * @author    GE Company / @Capital HQ Genius Dev
 * @copyright Copyright (c) 2013 General Electric Company
 */
?>
<!doctype html>
<html>
    <head>
        <title>Timesheets</title>
        <link rel=stylesheet type=text/css href="/css/app.css">
        
    </head>
    <body>               
        <ul>
            <li>Exception:123 <?php echo $this->exception ?>  </li>
            <li>Message: <?php echo $this->message ?> </li>            
        </ul>
    </body>
</html>